export class route {
  static readonly PAGE_HOME: string = 'pages/Home'
  static readonly PAGE_LOGIN: string = 'pages/Login'
  static readonly PAGE_CHAT: string = 'pages/Chat'
  static readonly PAGE_PRODUCT_DETAIL: string = 'pages/ProductDetail'
  static readonly PAGE_CHAT_HISTORY: string = 'pages/ChatHistory'
  static readonly DIALOG_LOGIN_PROMPT: string = 'dialogs/LoginPrompt'  // ← 新增是否登录弹窗
}

export const NAV_ID = 'MainNavigation'
